# Generated by Django 5.2.6 on 2025-09-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosdef', models.CharField(default='aucun', max_length=20)),
                ('tef', models.CharField(default='aucun', max_length=20)),
                ('bon_caisse', models.CharField(default='aucun', max_length=20)),
                ('mandat_paiement', models.CharField(default='aucun', max_length=20)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('dostype', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('termine', 'Terminé'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
            ],
        ),
    ]
