# Generated by Django 5.2.6 on 2025-09-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='dostype',
            field=models.CharField(default='aucun', max_length=50),
        ),
    ]
