# Generated by Django 5.2.6 on 2025-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_alter_dossier_dostype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='bon_caisse',
            field=models.CharField(blank=True, default='aucun', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='dosdef',
            field=models.CharField(blank=True, default='aucun', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='dostype',
            field=models.CharField(blank=True, default='aucun', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='mandat_paiement',
            field=models.CharField(blank=True, default='aucun', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='tef',
            field=models.CharField(blank=True, default='aucun', max_length=20, null=True),
        ),
    ]
